#! /bin/sh
# shellcheck disable=SC2034,SC2154
# > Default Locations
# @ ./Environment/core/dirs.sh

#| Top-level DOTS Directories
DOTS_BIN="${DOTS_BIN:-"${DOTS}/Bin"}" export DOTS_BIN
DOTS_CACHE="${DOTS_CACHE:-"${DOTS}/Cache"}" export DOTS_CACHE
DOTS_CFG="${DOTS_CFG:-"${DOTS}/Configuration"}" export DOTS_CFG
DOTS_DLD="${DOTS_DLD:-"${DOTS}/Downloads"}" export DOTS_DLD
DOTS_DOC="${DOTS_DOC:-"${DOTS}/Documentation"}" export DOTS_DOC
DOTS_ENV="${DOTS_ENV:-"${DOTS}/Environment"}" export DOTS_ENV
DOTS_LOG="${DOTS_LOG:-"${DOTS}/Log"}" export DOTS_LOG
DOTS_MOD="${DOTS_MOD:-"${DOTS}/Modules"}" export DOTS_MOD
DOTS_RES="${DOTS_RES:-"${DOTS}/Assets"}" export DOTS_RES
DOTS_TODO="${DOTS_TODO:-"${DOTS}/Tasks"}" export DOTS_TODO
DOTS_TEMPLATES="${DOTS_TEMPLATES:-"${DOTS}/Templates"}" export DOTS_TEMPLATES

#| User Directories
DOCUMENTS="${DOCUMENTS:-"${HOME}/Documents"}" export DOCUMENTS
DOWNLOADS="${DOWNLOADS:-"${HOME}/Downloads"}" export DOWNLOADS
MUSIC="${MUSIC:-"${HOME}/Music"}" export MUSIC
PHOTOS="${PHOTOS:-"${HOME}/Pictures"}" export PHOTOS
VIDEOS="${VIDEOS:-"${HOME}/Videos"}" export VIDEOS

#| System Directories
APPDATA="${APPDATA:-"${HOME}/AppData"}" export APPDATA



sys_INFO="$(
  printf "%s %s | %s@%s | %s" \
    "$(os.type.fetch)" \
    "$(os.distro.fetch)" \
    "$(username.fetch)" \
    "$(hostname.fetch)" \
    "$(basename "$(shell.fetch)")"
)"

sys_LABEL="$(
  printf "%s@%s on %s %s" \
    "$(username.fetch)" \
    "$(hostname.fetch)" \
    "$(os.type.fetch)" \
    "$(os.distro.fetch)"
)"

TIMESTAMP="$(date +%F_%H-%M)"

if [ -d "${PIC_DIR}/Wallpapers" ]; then
  WALLPAPERS="${PIC_DIR}/Wallpapers"
elif [ -d "${HOME}/Pictures/wallpapers" ]; then
  WALLPAPERS="${HOME}/Pictures/wallpapers"
else
  WALLPAPERS="${DOTS_RES}/Images/wallpaper"
fi




# | BIN
DOTS_BIN="$DOTS/Bin"
DOTS_BIN_CORE="$DOTS_BIN/core"
DOTS_BIN_UTIL="$DOTS_BIN/utility"
DOTS_BIN_IMPORT="$DOTS_BIN/import"
DOTS_BIN_PRJ="$DOTS_BIN/project"
DOTS_BIN_MISC="$DOTS_BIN/misc"

# | CFG
DOTS_CFG="$DOTS/Configuration"
DOTS_CFG="$DOTS_CFG/apps"
DOTS_CFG="$DOTS_CFG/tools"
DOTS_CFG="$DOTS_CFG/cli"

# | ENV
DOTS_ENV="$DOTS/Environment"
DOTS_ENV_CTX="$DOTS_ENV/context"
DOTS_ENV_EXP="$DOTS_ENV/export"
DOTS_ENV_BASE="$DOTS_ENV_EXP/base"
DOTS_ENV_CORE="$DOTS_ENV_EXP/core"
DOTS_ENV_UTIL="$DOTS_ENV_EXP/utility"
DOTS_ENV_IMPORT="$DOTS_ENV_EXP/import"
DOTS_ENV_APP="$DOTS_ENV_EXP/package"
DOTS_ENV_PRJ="$DOTS_ENV_EXP/project"

# | KEYS
DOTS_KEY="$DOTS/Keys"

# | General
codeDOTS="$DOTS_CFG/vscode/Dotfiles.code-workspace"
codeRUST="$DOTS_CFG/vscode/Rust.code-workspace"
codeNIX="$DOTS_CFG/vscode/Nix.code-workspace"
DOTS_FONT="$DOTS_RES/Fonts"
KEYMAPS="$DOTS_CFG/utilities/sxhkd"
ASCII="$DOTS_RES/Images/ascii"

# @_____________________________________________________________________ GUIX<|
DOTS_GUIX="$DOTS_CFG/utilities/guix"
DOTS_NIX="$DOTS_CFG/nixos"
DOTS_WSLnix="$DOTS_CFG/NixWSL"
DOTS_loaded_apps="$DOTS_LOG/loaded_apps"
