# Module: lib/default.nix
# Purpose: mkOpenClawConfig and mkSecureService helper functions.
# Maintainer: openclaw-flake contributors
{lib, ...}: {
  # Re-export all lib helpers as a single attrset.
  # Import as: `inputs.self.lib` or via blueprint's lib discovery.
  lib = {
    inherit (import ./options.nix {inherit lib;}) openclawOptionTypes;

    # mkOpenClawConfig :: attrset -> attrset
    # Merges caller-supplied overrides on top of sensible defaults for
    # the services.openclaw option subtree.
    mkOpenClawConfig = overrides:
      lib.recursiveUpdate {
        enable = true;
        port = 8080;
        host = "127.0.0.1";
        logLevel = "info";
        openFirewall = false;
        tls.enable = false;
        tls.certFile = null;
        tls.keyFile = null;
        extraConfig = {};
        allowedIPs = [];
      }
      overrides;

    # mkSecureService :: { name, execStart, dataDir, extraServiceConfig? } -> systemd.services attrs
    # Returns a hardened systemd service attrset suitable for merging into
    # config.systemd.services.<name>.  Applies the same hardening posture
    # used in modules/openclaw/service.nix.
    mkSecureService = {
      name,
      execStart,
      dataDir,
      extraServiceConfig ? {},
    }: {
      description = "Hardened ${name} service (generated by mkSecureService)";
      wantedBy = ["multi-user.target"];
      after = [
        "network-online.target"
        "nss-lookup.target"
      ];
      wants = ["network-online.target"];

      serviceConfig =
        lib.recursiveUpdate {
          ExecStart = execStart;
          Restart = "on-failure";
          RestartSec = "5s";
          DynamicUser = true;
          PrivateTmp = true;
          PrivateDevices = true;
          ProtectSystem = "strict";
          ProtectHome = true;
          NoNewPrivileges = true;
          RestrictSUIDSGID = true;
          MemoryDenyWriteExecute = true;
          LockPersonality = true;
          RestrictRealtime = true;
          CapabilityBoundingSet = [""];
          RestrictAddressFamilies = [
            "AF_INET"
            "AF_INET6"
            "AF_UNIX"
          ];
          IPAddressDeny = "any";
          ProtectKernelTunables = true;
          ProtectKernelModules = true;
          ProtectControlGroups = true;
          SystemCallFilter = [
            "@system-service"
            "~@privileged"
            "~@resources"
          ];
          SystemCallArchitectures = "native";
          ReadWritePaths = [dataDir];
          StateDirectory = name;
          UMask = "0027";
        }
        extraServiceConfig;
    };
  };
}
