#!/bin/bash

#@ Get the directory of the currently running script
BDOTDIR="${SHELL_HOME:-"$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"}"

#@ Export BDOTDIR
export BDOTDIR
eval "$(starship init bash)"

# Function to load files from a directory
# Parameters:
#   $1: Directory path
#   $2: File extension (default is "bash")
# init_config() {
#   conf_files="$(find "$1" -type f)"

#   for conf in $conf_files; do
#     if [ -r "$conf" ]; then
#       # time . "$conf"
#       . "$conf"
#     else
#       printf "File not readable:  %s" "$conf"
#     fi
#   done
# }

# Load resources and functions
# init_config "$BDOTDIR/resources"
# init_config "$BDOTDIR/functions"
