[global]
excludes = ["treefmt.toml", "generated.nix"]

[formatter.nixfmt]
command = "nixfmt"
includes = ["*.nix"]
priority = 1

# [formatter.alejandra]
# command = "alejandra"
# includes = ["*.nix"]
# priority = 1

# [formatter.deadnix]
# command = "deadnix"
# options = ["-e"]
# includes = ["*.nix"]
# priority = 2

# [formatter.statix]
# command = "statix"
# options = ["check"]
# includes = ["*.nix"]
# priority = 3

[formatter.rust]
command = "rustfmt"
includes = ["*.rs"]

[formatter.shellcheck]
command = "shellcheck"
includes = ["*.sh"]
options = ["-i", "2", "-s"]
priority = 2

[formatter.shfmt]
command = "shfmt"
includes = ["*.sh"]
options = ["-i", "2", "-s"]

[formatter.python]
command = "ruff"
includes = ["*.py"]
options = ["format", "--quiet"]

[formatter.json]
command = "jq"
includes = ["*.json", "*.jsonc"]
options = ["--indent", "2", "--sort-keys"]

[formatter.toml]
command = "taplo"
includes = ["*.toml"]
options = ["fmt"]

[formatter.markdown]
command = "markdownlint"
includes = ["*.md"]
options = ["--prose-wrap", "always", "--write"]
