#! /bin/sh
# shellcheck disable=SC2034,SC2154

#| Bash
BDOTDIR="${DOTS_CFG}/bash"
ZDOTDIR="${DOTS_CFG}/zsh"
FDOTDIR="${DOTS_CFG}/fish"
NDOTDIR="${DOTS_CFG}/nushell"
GDOTDIR="${DOTS_CFG}/git"
PDOTDIR="${DOTS_CFG}/powershell"
SSHDIR="$HOME/.ssh"

# | Config Files
RC_bash_home="$HOME/.bashrc"
RC_bash="$BDOTDIR/config"
RC_dash="$DDOTDIR/.config"
RC_zsh="$ZDOTDIR/.config"
RC_fish="$FDOTDIR/.config"
RC_nush="$NDOTDIR/.config"
RC_git="$GDOTDIR/global/config"
RC_pwsh="$PDOTDIR/config/pshrc.ps1"
RC_ssh="$SSHDIR/config"
RC_init="$DOTS/.dotsrc"
