= Biblical Principles

Scripture does not treat depression as a stranger to faithful life. Instead, it gives language for the very experiences that often accompany Major Depressive Disorder: hopelessness, sorrow, guilt, isolation, fatigue, and the loss of meaning. Psalm 34:18 presents God as near to the brokenhearted, which is pastorally significant because depression often tells a person that God is distant or uninterested. The verse does not erase pain; it counters the lie that suffering means abandonment. For church counselling, that means the first response should not be correction but presence, reassurance, and patient care.

The Psalms of lament are especially helpful because they normalise depressive expression before God. Psalm 42 describes a person who is downcast, spiritually disoriented, and painfully self-aware, yet still turns toward hope rather than despair. Psalm 88 goes further by presenting almost uninterrupted darkness, which is important for people whose depression includes numbness, emptiness, or the inability to feel relief. These psalms show that faithful prayer can include honesty without quick resolution. In pastoral care, they permit the depressed person to say, in effect, “This is what I feel,” without being shamed for not sounding triumphant.

The story of Elijah in 1 Kings 19 is also relevant. After intense ministry stress, Elijah becomes exhausted, afraid, withdrawn, and ready to die. God’s response is instructive: He first provides rest, food, and gentle encounter before He gives further direction. That pattern is meaningful for depression because many sufferers need rest, bodily care, and safety before they are ready for exhortation. Likewise, Matthew 11:28–30 presents Jesus as one who invites the weary to come for rest, which speaks directly to people burdened by heaviness rather than mere guilt. Galatians 6:2 calls the church to carry one another’s burdens, showing that depression should not be faced alone. Finally, Romans 12:2 supports the renewal of the mind, not as a slogan for positive thinking, but as a call to reject despairing patterns and receive God’s truth.

Taken together, these passages show that biblical care for depression should be gentle, communal, and hope-filled. Scripture helps the church address the inner life of the depressed person without reducing depression to sin, weak faith, or lack of effort.
