= Counselling Theories

Cognitive Behavioural Therapy is especially relevant to Major Depressive Disorder because depression is often maintained by negative automatic thoughts and cognitive distortions. A depressed person may repeatedly think, “I am worthless,” “Nothing will ever change,” “I have failed everyone,” or “There is no point trying.” CBT helps the person notice these thoughts, test them against evidence, and replace rigid or distorted conclusions with more balanced interpretations @beck2011. This is not a denial of suffering; it is a practical method for interrupting hopelessness, self-blame, and the mental narrowing that often accompanies depression.

CBT is also useful because depression commonly produces withdrawal. When people stop sleeping well, stop socialising, and stop engaging in meaningful activity, the low mood often deepens. Behavioural activation addresses this pattern by helping the person schedule small, realistic actions that reconnect them to routine, pleasure, responsibility, and contact with others. In a church context, that may include returning to worship, walking with a trusted believer, completing one manageable task at home, or taking one step toward professional help. For MDD, CBT therefore offers both cognitive and behavioural tools.

Person-centred Therapy contributes a different but equally important dimension. Carl Rogers argued that growth is more likely when the counsellor offers empathy, unconditional positive regard, and genuineness @rogers1961. Those qualities matter in depression because many sufferers already feel ashamed, defective, or emotionally exhausted. A person-centred counsellor does not rush to fix the person; instead, the counsellor listens deeply, reflects emotion accurately, and provides emotional safety. That atmosphere can reduce shame and make it possible for the depressed person to speak honestly about suicidal thoughts, spiritual confusion, or feelings of emptiness.

In church-based care, the value of person-centred therapy is that it mirrors the best kind of pastoral presence: patient listening without judgment. The counsellor’s aim is not simply to correct unhelpful thinking, but to help the person feel understood enough to remain engaged in care. Used together, CBT and person-centred therapy provide structure and warmth, change and safety, truth and compassion.
