#!/bin/sh
# https://stackoverflow.com/a/52586842
# shellcheck disable=SC3000-SC4000

case $1 in
-d | --verbose)
  VERBOSE=true
  shift
  ;;
*) ;;
esac

user_id="${EUID:-"${user_id}"}"

if  [ "${user_id}" -eq 0 ]; then
  if [ -n "${VERBOSE}" ]; then
    printf "You are the root almighty!\n"
  fi
  exit 0
else
  if [ -n "${VERBOSE}" ]; then
    printf "You are just an ordinary user.\n" >&2
  fi
  exit 1
fi
