[global]
  excludes = [
    ".dotsrc",
    "LICENSE",
    "**/node_modules/**",
    "**/target/**",
    "**/.git/**",
    "**/dist/**",
    "**/build/**",
    "**/review/**",
    "**/archive/**",
    "*.lock",
    "Assets/**",
    "*.diff",
    "*.patch",
    "AGENTS.md",
    "**/dump.nix",
    "**/.bin/**",
    "**/.config/**",
    "**README.md",                                # TODO Temporary
    ".zed/**",                                    # TODO Temporary
    "Configuration/**",                           # TODO Temporary
    "Documentation/**",                           # TODO Temporary
    "Environment/**",                             # TODO Temporary
    "Modules/global/**",                          # TODO Temporary
    "Modules/nixos/configurations/hosts/QBX/**",  # TODO Temporary
    "Modules/nixos/scripts/**",                   # TODO Temporary
    "Review/**",                                  # TODO Temporary
    "Scripts/**",                                 # TODO Temporary
    "Tasks/**",                                   # TODO Temporary
    "Templates/**",                               # TODO Temporary
  ]

# -- Nix
[formatter.alejandra]
  includes = ["*.nix"]
  priority = 1
  command = "alejandra"

[formatter.statix]
  includes = ["*.nix"]
  priority = 2
  command = "sh"
  options = ["-c", "for f in \"$@\"; do statix check \"$f\"; done"]

# -- Rust
[formatter.rust]
  includes = ["*.rs"]
  priority = 1
  command = "rustfmt"
  # options = ["--edition", "2024"]

[formatter.leptosfmt]
  includes = ["*.rs"]
  priority = 2
  command = "leptosfmt"

# -- Shell Script
[formatter.shellcheck]
  includes = [
    "*.sh",
    ".env*",
    ".shellcheckrc",
    "*.bash",
    ".bash*",
    "Bin/shellscript/**",
  ]
  excludes = ["*.md", "*.ps1", "*.psm1", "*.txt", "*.log"]
  priority = 1
  command = "shellcheck"
  options = ["--rcfile", ".shellcheckrc"]

[formatter.shfmt]
  includes = [
    "*.sh",
    "*.dotsrc",
    "*.env*",
    "*.shellcheckrc",
    "*.gitignore",
    "*.ignore",
  ]
  excludes = ["*.md", "*.ps1", "*.psm1", "*.txt", "*.log"]
  priority = 2
  command = "shfmt"
  options = [
    "--apply-ignore",
    "--binary-next-line",
    "--space-redirects",
    "--case-indent",
    "--indent",
    "2",
    "--posix",
    "--write",
  ]

# -- Configuration
[formatter.toml]
  includes = ["*.toml"]
  command = "tombi"
  options = ["format", "--offline"]
  priority = 2

[formatter.ruff]
  includes = ["*.py"]
  command = "sh"
  options = [
    "-euc",
    "command -v ruff >/dev/null || exit 0",
    "for file in \"$@\"; do ruff format --quiet \"$file\"; done",
  ]

[formatter.stylua]
  includes = ["*.lua"]
  command = "stylua"

# -- Markup
[formatter.dprint]
  includes = [
    "*.astro",
    "*.css",
    "*.html",
    "*.json",
    "*.jsonc",
    "*.less",
    "*.md",
    "*.sass",
    "*.scss",
    "*.svelte",
    "*.vue",
    "*.yaml",
    "*.yml",
    "Dockerfile",
  ]
  priority = 1
  command = "dprint"
  options = ["fmt", "--stdin", "{{filename}}"]

[formatter.yamlfmt]
  includes = ["*.yaml", "*.yml"]
  priority = 2
  command = "yamlfmt"
  options = ["-formatter", "retain_line_breaks=true"]

[formatter.actionlint]
  includes = [
    ".github/workflows/*.yml",
    ".github/workflows/*.yaml",
    ".gitea/workflows/*.yml",
    ".gitea/workflows/*.yaml",
    ".forgejo/workflows/*.yml",
    ".forgejo/workflows/*.yaml",
  ]
  # excludes = []
  command = "actionlint"
  options = []

[formatter.typstyle]
  includes = ["*.typ", "*.typst"]
  command = "typstyle"
