excludes = [".dotsrc", "LICENSE", "**/node_modules/**", "**/target/**", "**/.git/**", "**/dist/**", "**/build/**", "**/review/**", "**/archive/**", "*.lock", "Assets/**", "*.diff", "*.patch", "AGENTS.md", "**/dump.nix", "**/.bin/**", "**/.config/**", "**README.md", ".zed/**", "Configuration/**", "Documentation/**", "Environment/**", "Modules/global/**", "Modules/nixos/configurations/hosts/QBX/**", "Modules/nixos/scripts/**", "Review/**", "Scripts/**", "Tasks/**", "Templates/**", "*.lock", "*.patch", "package-lock.json", "go.mod", "go.sum", ".gitattributes", ".gitignore", ".gitmodules", ".hgignore", ".svnignore", "LICENSE"]

[formatter.actionlint]
command = "/nix/store/ypcd7ghn7nwgpzi9sm0fswk7rgwslyq6-actionlint-1.7.12/bin/actionlint"
excludes = []
includes = [".github/workflows/*.yml", ".github/workflows/*.yaml", ".gitea/workflows/*.yml", ".gitea/workflows/*.yaml", ".forgejo/workflows/*.yml", ".forgejo/workflows/*.yaml"]
options = []

[formatter.alejandra]
command = "/nix/store/kq61zzri6yliqysbrwnc3mhsqddwwlrh-alejandra-4.0.0/bin/alejandra"
excludes = []
includes = ["*.nix"]
options = []

[formatter.dprint]
command = "/nix/store/ik6xkpy0wydjamvg0xg4h9dp7mk4j8n7-dprint-0.55.2/bin/dprint"
excludes = []
includes = ["*.json", "*.jsonc", "*.md", "*.yaml", "*.yml", "*.css", "*.scss", "*.sass", "*.less"]
options = ["fmt", "--allow-no-files", "--config", "dprint.json"]
priority = 1

[formatter.harper]
command = "/nix/store/yvb520m1l108rnywc0ch4jp6kcg91wcb-harper-2.7.0/bin/harper-ls"
excludes = []
includes = ["Documentation/**/*.md", "Documentation/**/*.typ"]
options = ["check", "--format", "short"]
priority = 1

[formatter.leptosfmt]
command = "/nix/store/vkvj6ragls3z4vlrvdd83bbskq5zy07d-leptosfmt-0.1.33/bin/leptosfmt"
excludes = []
includes = ["*.rs"]
options = []
priority = 2

[formatter.ruff-check]
command = "/nix/store/z2078an0s17i6phm99np502fzj5iybd8-ruff-0.16.2/bin/ruff"
excludes = []
includes = ["*.py", "*.pyi"]
options = ["check", "--fix"]
priority = 2

[formatter.ruff-format]
command = "/nix/store/z2078an0s17i6phm99np502fzj5iybd8-ruff-0.16.2/bin/ruff"
excludes = []
includes = ["*.py", "*.pyi"]
options = ["format"]
priority = 1

[formatter.rustfmt]
command = "/nix/store/k2hwcha2p1fy0v0py34vq3jyvwqk339p-rustfmt-1.97.1/bin/rustfmt"
excludes = []
includes = ["*.rs"]
options = ["--config", "skip_children=true", "--edition", "2024"]
priority = 1

[formatter.shellcheck]
command = "/nix/store/arx11b315ynql817kgf0548307zm8w4r-shellcheck-0.11.0-bin/bin/shellcheck"
excludes = []
includes = ["*.sh", "*.bash", "*.envrc", "*.envrc.*"]
options = ["--rcfile", ".shellcheckrc"]
priority = 1

[formatter.shfmt]
command = "/nix/store/83klmqyg64fr3zv5zbnzb0fc6kda29f2-shfmt-3.13.1/bin/shfmt"
excludes = []
includes = ["*.sh", "*.bash", "*.envrc", "*.envrc.*"]
options = ["-w", "--apply-ignore", "--binary-next-line", "--space-redirects", "--case-indent", "-i", "2", "-s"]
priority = 2

[formatter.statix]
command = "/nix/store/ib982jfac2qyf18w7b64rd9srxjpdlbz-statix-wrapper"
excludes = []
includes = ["*.nix"]
options = []

[formatter.stylua]
command = "/nix/store/w6mr02wa797dg82av68f44wn8jxdb3ky-stylua-2.5.2/bin/stylua"
excludes = []
includes = ["*.lua"]
options = []

[formatter.tombi]
command = "/nix/store/6mzj1z8cy2fji4cr4lmmsn6r7d5sqkp3-tombi-1.2.7/bin/tombi"
excludes = []
includes = ["*.toml"]
options = ["format", "--offline"]
priority = 1

[formatter.typos]
command = "/nix/store/j4ldqh2achvl4zhvap4kchn8nb9frz85-typos-1.49.0/bin/typos"
excludes = []
includes = ["*"]
options = ["--write-changes", "--force-exclude"]

[formatter.typstyle]
command = "/nix/store/dy1mj9a70fmvrbfn5wg7vh6q8k1y70m3-typstyle-0.15.0/bin/typstyle"
excludes = []
includes = ["*.typ", "*.typst"]
options = ["-i"]
