[default]
extend-ignore-identifiers-re = []
extend-ignore-words-re = []
extend-ignore-re = ["typ", "nd"]

[default.extend-identifiers]

[default.extend-words]

[type.nix]
extend-glob = []
extend-ignore-identifiers-re = []
extend-ignore-words-re = []
extend-ignore-re = ["ags", "BaC", "fo"]

[type.sh]
extend-glob = ["**/day"]
extend-ignore-identifiers-re = []
extend-ignore-words-re = []
extend-ignore-re = ["nd"]
