dictionaries = []
words = [
  "deadnix",
  "jsonc",
  "markdownlint",
  "nixfmt",
  "rustfmt",
  "shellcheck",
  "shfmt",
  "starship",
  "statix",
  "taplo",
  "treefmt",
]
flag_words = []
ignore_paths = []
