dictionaries = ["en_us"]
words = [
  "deadnix",
  "jsonc",
  "markdownlint",
  "nixfmt",
  "rustfmt",
  "shellcheck",
  "shfmt",
  "starship",
  "statix",
  "taplo",
  "treefmt",
  "fastfetch",
  "coreutils",
  "bdotrc",
  "bdotdir",
  "bashrc",
  "bash_profile",
  "bash_aliases",
  "bash_functions",
  "bash_logout",
  "bash_history",
  "bash_prompt",
  "bashrc.d",
  "bash_profile.d",
  "bash_aliases.d",
  "bash_functions.d",
  "bash_logout.d",
  "bash_prompt.d",
  "bash_history",
  "realpath",
  "dotsrc",
  "direnv",
  "fastfetch",
  "posix",
  "jsonc",
  "rosé",
  "nixos",
  "starship",
  "thefuck",
  "treefmt",
  "wsl",
  "zoxide",
]
flag_words = []
ignore_paths = []
