# https://numtide.github.io/devshell

[[commands]]
category = "Interactive Shell & Scripting"
name = "bash"
package = "bashInteractive"

[[commands]]
category = "Information Management"
package = "bat"

[[commands]]
category = "Information Management"
package = "btop"

[[commands]]
category = "Environment Management"
package = "direnv"

[[commands]]
category = "Environment Management"
package = "eza"

[[commands]]
category = "Environment Management"
package = "fd"

[[commands]]
category = "Interactive Shell & Scripting"
package = "fish"

[[commands]]
category = "Information Management"
package = "fastfetch"

[[commands]]
category = "Environment Management"
package = "fzf"

[[commands]]
category = "Interactive Shell & Scripting"
package = "just"

[[commands]]
category = "Environment Management"
package = "lsd"

[[commands]]
category = "Interactive Shell & Scripting"
name="nu"
package = "nushell"

[[commands]]
category = "Interactive Shell & Scripting"
name = "pwsh"
package = "powershell"

[[commands]]
category = "Environment Management"
package = "rbw"

[[commands]]
category = "Information Management"
name = "rg"
package = "ripgrep"

[[commands]]
category = "Environment Management"
package = "yazi"

[[commands]]
category = "Environment Management"
package = "zoxide"

[[commands]]
category = "Interactive Shell & Scripting"
package = "zsh"

[devshell]
packages = [
  "bat",
  "btop",
  "direnv",
  "eza",
  "fastfetch",
  "fd",
  "fzf",
  "glib",
  "jq",
  "lsd",
  "ripgrep",
  "thefuck",
  "lesspipe",
  "yazi",
  "zoxide",
]
