[env]
MISE_CONF="C:\\Users\\Administrator\\.config\\mise\\config.toml"
EDITOR = "helix"
PAGER = "bat --color=always --style=plain"

[hooks]
enter = "mise install --quiet"
leave = "echo Goodbye!"
postinstall = "mise clean"

[settings]
experimental = true
# lockfile = true
# quiet = true
windows_shim_mode = "symlink"

[tasks.update]
description = "Update all global tools"
alias = "upd"
run = [
  "mise self-update",
  "mise install",
  "mise upgrade",
]

[tasks.clean]
description = "Clean up caches"
alias = "cln"
run = "mise cache prune"

[tasks.tools]
alias = "reg"
description = "List available tools from the registry filtered by a search term"
usage = '''
arg "pattern" "search pattern to filter tools" default=""
'''
run = "mise registry | rg -- %USAGE_PATTERN%"

[tools]
bat = "latest"
deno = "latest"
eza = "latest"
cargo-binstall = "latest"
"cargo:treefmt" = "latest"
# "cargo:sqruff" = "latest"
# docker-cli = "latest"
# docker-compose = "latest"
# podman = "latest"
# docker-slim = "latest"
jujutsu = "latest"
ripgrep = "latest"
taplo = "latest"
tokei = "latest"
usage = "latest"
uv = "latest"
watchexec = "latest"
dust = "latest"
fastfetch = "latest"
cosign = "latest"
just = "latest"
typos = "latest"
typst = "latest"
typstyle = "latest"
yamlfmt = "latest"
