# Beryllium

hide_ascii = true
key_color  = "#7067CF"
separator  = ""
spacing    = 3

[box]
border  = "plain"
visible = true

[palette]
glyph   = "○  "
visible = true

[bar]
glyph           = "○"
hide_delimiters = true
visible         = true

[box.inner_margin]
x = 2
y = 1

[custom_ascii]
color = "#FF7001"
