# Craole

hide_ascii = false
key_color = "Green"
padding = 1
prefer_small_ascii = false
separator = " | "
separator_color = "Green"
spacing = 0

[custom_ascii]
color = "Green"
path = "~/.config/macchina/images/terminal.ascii"

[palette]
glyph = " ❇ "
type = "Light"
visible = true

[bar]
glyph = "■"
hide_delimiters = false
symbol_close = ']'
symbol_open = '['
visible = false

[box]
border = "plain"
title = " Craole "
visible = false

[box.inner_margin]
x = 2
y = 1

[randomize]
# key_color = false
pool = "hexadecimal"
separator_color = false

[keys]
backlight = "    Brightness | "
battery = "       Battery | "
cpu = "           CPU | "
cpu_load = "      CPU Load | "
de = "   Desktop Env | "
distro = "  Distribution | "
host = "          Host | "
kernel = "        Kernel | "
local_ip = "    IP Address | "
machine = "       Machine | "
memory = "        Memory | "
os = "            OS | "
packages = "      Packages | "
resolution = "    Resolution | "
shell = "         Shell | "
terminal = "      Terminal | "
uptime = "        Uptime | "
wm = "Window Manager | 拓"
