#!/bin/sh

#> Info
_APP="helix"
_NAME="Helix Editor"

#> TYPE
_TYPE="tty"

#> Config
_HOME="${DOTS_CFG}/${_APP}"
_EXT="toml"
_CFG="${_HOME}/${_APP}.${_EXT}"

#> CMD
_CMD="hx"
[ -f "$_CFG" ] && _CMD="${_CMD} --config ${_CFG}"

#> LINK
src="$_HOME"
