#!/bin/sh

#> Info
_APP="starship"
_NAME="Starship Prompt"
_TYPE="tty"

#> THEME
: <<THEMES
  bracketed-segments
  craole
  nerd-font-symbols
  no-nerd-font
  pastel-powerline
  tokyo-night
THEMES

theme="craole"

#> Config
DOTS_CFG="${DOTS_CFG:-$DOTS/Config/cli}"
_HOME="${DOTS_CFG}/${_APP}"
_EXT="toml"
STARSHIP_CACHE="${CACHE_HOME}/${_APP}"
STARSHIP_CONFIG="${_HOME}/themes/${theme}.${_EXT}"

#> LINK
src="$_THEME"
lnk="$_CFG"
export STARSHIP_CONFIG STARSHIP_CACHE
