# shellcheck shell=sh
#shellcheck enable=all
if [ -n "${HERMES_ENV_SH:-}" ] && [ -f "$HERMES_ENV_SH" ]; then
  # shellcheck disable=SC1090
  . "$HERMES_ENV_SH"
fi

: "${HERMES_HOME:?HERMES_HOME not set}"
: "${HERMES_ENV_SH:?HERMES_ENV_SH not set}"

HERMES_DISCORD_BOT_TOKEN="$(env_get DISCORD_BOT_TOKEN)"
HERMES_DISCORD_ALLOWED_USERS="$(env_get DISCORD_ALLOWED_USERS)"
HERMES_DISCORD_HOME_CHANNEL="$(env_get DISCORD_HOME_CHANNEL)"
HERMES_DISCORD_HOME_CHANNEL_NAME="$(env_get DISCORD_HOME_CHANNEL_NAME)"
export HERMES_DISCORD_BOT_TOKEN HERMES_DISCORD_ALLOWED_USERS
export HERMES_DISCORD_HOME_CHANNEL HERMES_DISCORD_HOME_CHANNEL_NAME
