[manager]
linemode       = "mtime"
ratio          = [1, 2, 2]
sort_by        = "natural"
sort_dir_first = true

[preview]
max_height = 1024
max_width  = 1024

[plugin]
prepend_previewers = [
  { mime = "application/*zip", run = "ouch" },
  { mime = "application/x-tar", run = "ouch" },
  { mime = "application/x-bzip2", run = "ouch" },
  { mime = "application/x-7z-compressed", run = "ouch" },
  { mime = "application/x-rar", run = "ouch" },
  { mime = "application/x-xz", run = "ouch" },
]

[opener]
display      = [{ run = 'zathura "$@"', desc = "Show in Zathura" }]
edit         = [{ run = 'nvim "$@"', block = true }]
extract      = [{ run = 'ouch d -y "$@"', desc = "Extract here with ouch" }]
generic_open = [{ run = 'xdg-open "$@"', desc = "Open" }]

[open]
append_rules = [{ name = "*", use = "generic_open" }]
prepend_rules = [
  { name = "*.epub", use = "display" },
  { name = "*.pdf", use = "display" },
]
