import importlib.util
import pathlib
import tempfile
import unittest


ROOT = pathlib.Path(__file__).parents[1]
SCRIPT = ROOT / "scripts" / "sync_toolchain.py"

spec = importlib.util.spec_from_file_location("sync_toolchain", SCRIPT)
module = importlib.util.module_from_spec(spec)
assert spec.loader is not None
spec.loader.exec_module(module)


class SyncToolchainTests(unittest.TestCase):
    def test_generates_mise_and_rust_adapters_from_canonical_file(self):
        with tempfile.TemporaryDirectory() as directory:
            root = pathlib.Path(directory)
            source = root / ".config" / "toolchain.toml"
            source.parent.mkdir()
            source.write_text(
                """schema = 1\n\n[tools]\nrust = \"1.85.0\"\nnode = \"22.14.0\"\npnpm = \"10.6.1\"\n"""
            )

            module.sync(root)

            self.assertEqual(
                (root / "rust-toolchain.toml").read_text(),
                """# Generated by scripts/sync_toolchain.py; do not edit.\n[toolchain]\nchannel = \"1.85.0\"\n""",
            )
            self.assertIn("# Generated by scripts/sync_toolchain.py", (root / ".config" / "mise.toml").read_text())
            self.assertIn('rust = "1.85.0"', (root / ".config" / "mise.toml").read_text())
            self.assertIn('node = "22.14.0"', (root / ".config" / "mise.toml").read_text())

    def test_check_detects_stale_generated_files(self):
        with tempfile.TemporaryDirectory() as directory:
            root = pathlib.Path(directory)
            source = root / ".config" / "toolchain.toml"
            source.parent.mkdir()
            source.write_text('schema = 1\n[tools]\nrust = "1.85.0"\n')
            module.sync(root)
            source.write_text('schema = 1\n[tools]\nrust = "1.86.0"\n')

            self.assertFalse(module.check(root))
            module.sync(root)
            self.assertTrue(module.check(root))

    def test_rejects_unknown_schema(self):
        with tempfile.TemporaryDirectory() as directory:
            root = pathlib.Path(directory)
            source = root / ".config" / "toolchain.toml"
            source.parent.mkdir()
            source.write_text('schema = 2\n[tools]\nrust = "1.85.0"\n')

            with self.assertRaises(ValueError):
                module.sync(root)


if __name__ == "__main__":
    unittest.main()
