#!/bin/sh

CMD_BAT="${CMD_BAT:-$(command -v bat 2>/dev/null)}"
_pager() {
  if [ -x "${CMD_BAT:-}" ]; then
    "${CMD_BAT}" --color=always --style="numbers"
  else
    less -N -R
  fi
}

printf "%s\n" "$*" | _pager
