#!/bin/sh
# shellcheck disable=SC1091

#| Load variables
. "${DOTS_ENV_CTX:?}/sway"
. "${DOTS_ENV_CTX:?}/wayland"

#| Initialise with specific config
sway --config "${DESKTOP_HOME:?}/${DESKTOP_CONF:?}"
