# shellcheck shell=sh
#shellcheck enable=all
if [ -n "${HERMES_ENV_SH:-}" ] && [ -f "$HERMES_ENV_SH" ]; then
  # shellcheck disable=SC1090
  . "$HERMES_ENV_SH"
fi

: "${HERMES_HOME:?HERMES_HOME not set}"
: "${HERMES_ENV_SH:?HERMES_ENV_SH not set}"

HERMES_TELEGRAM_BOT_TOKEN="$(env_get TELEGRAM_BOT_TOKEN)"
HERMES_TELEGRAM_ALLOWED_USERS="$(env_get TELEGRAM_ALLOWED_USERS)"
HERMES_TELEGRAM_HOME_CHANNEL="$(env_get TELEGRAM_HOME_CHANNEL)"
HERMES_TELEGRAM_HOME_CHANNEL_NAME="$(env_get TELEGRAM_HOME_CHANNEL_NAME)"
export HERMES_TELEGRAM_BOT_TOKEN HERMES_TELEGRAM_ALLOWED_USERS
export HERMES_TELEGRAM_HOME_CHANNEL HERMES_TELEGRAM_HOME_CHANNEL_NAME

: "${HERMES_TELEGRAM_BOT_TOKEN:?TELEGRAM_BOT_TOKEN is not set in $HERMES_HOME/.env}"
: "${HERMES_TELEGRAM_ALLOWED_USERS:?TELEGRAM_ALLOWED_USERS is not set in $HERMES_HOME/.env}"
