#! /bin/sh
# shellcheck disable=SC2034,SC2154,SC1091

echo ADMIN
#| Output Control
DELIMITER="${DELIMITER:-"$(printf "\037")"}" export DELIMITER
LANG="$(locale -uU || printf "en_US.UTF-8")" export LANG
VERBOSITY="${verbosity:-"${VERBOSITY:-3}"}"
VERBOSITY_QUIET="${verbosity_quiet:-"${VERBOSITY_QUIET:-0}"}"
VERBOSITY_ERROR="${verbosity_error:-"${VERBOSITY_ERROR:-1}"}"
VERBOSITY_WARN="${verbosity_warn:-"${VERBOSITY_WARN:-2}"}"
VERBOSITY_INFO="${verbosity_info:-"${VERBOSITY_INFO:-3}"}"
VERBOSITY_DEBUG="${verbosity_debug:-"${VERBOSITY_DEBUG:-4}"}"
VERBOSITY_TRACE="${verbosity_trace:-"${VERBOSITY_TRACE:-5}"}"
export VERBOSITY VERBOSITY_QUIET VERBOSITY_ERROR VERBOSITY_WARN VERBOSITY_INFO VERBOSITY_DEBUG VERBOSITY_TRACE

#| Bin Directories
DOTS_BIN_BASH="${DOTS_BIN_BASH:-"${DOTS_BIN}/bash"}" export DOTS_BIN_BASH
DOTS_BIN_CMD="${DOTS_BIN_CMD:-"${DOTS_BIN}/cmd"}" export DOTS_BIN_CMD
DOTS_BIN_FISH="${DOTS_BIN_FISH:-"${DOTS_BIN}/fish"}" export DOTS_BIN_FISH
DOTS_BIN_NUSHELL="${DOTS_BIN_NUSHELL:-"${DOTS_BIN}/nushell"}" export DOTS_BIN_NUSHELL
DOTS_BIN_POWERSHELL="${DOTS_BIN_POWERSHELL:-"${DOTS_BIN}/powershell"}" export DOTS_BIN_POWERSHELL
DOTS_BIN_PYTHON="${DOTS_BIN_PYTHON:-"${DOTS_BIN}/python"}" export DOTS_BIN_PYTHON
DOTS_BIN_RUST="${DOTS_BIN_RUST:-"${DOTS_BIN}/rust"}" export DOTS_BIN_RUST
DOTS_BIN_SH="${DOTS_BIN_SH:-"${DOTS_BIN}/shellscript"}" export DOTS_BIN_SH
DOTS_BIN_SQL="${DOTS_BIN_SQL:-"${DOTS_BIN}/sql"}" export DOTS_BIN_SQL
DOTS_BIN_ZIG="${DOTS_BIN_ZIG:-"${DOTS_BIN}/zig"}" export DOTS_BIN_ZIG
DOTS_BIN_ZSH="${DOTS_BIN_ZSH:-"${DOTS_BIN}/zsh"}" export DOTS_BIN_ZSH
# pout_env "DOTS_BIN_BASH"
# pout_env "DOTS_BIN_CMD"
# pout_env "DOTS_BIN_FISH"
# pout_env "DOTS_BIN_NUSHELL"
# pout_env "DOTS_BIN_POWERSHELL"
# pout_env "DOTS_BIN_PYTHON"
# pout_env "DOTS_BIN_RUST"
# pout_env "DOTS_BIN_SH"
# pout_env "DOTS_BIN_SQL"
# pout_env "DOTS_BIN_ZIG"
# pout_env "DOTS_BIN_ZSH"

#| Resource Directories
DOTS_FONTS="${DOTS_FONTS:-"${DOTS_RES}/Fonts"}" export DOTS_FONTS
DOTS_IMAGES="${DOTS_IMAGES:-"${DOTS_RES}/Images"}" export DOTS_IMAGES
DOTS_SCRIPTS="${DOTS_SCRIPTS:-"${DOTS_RES}/Home"}" export DOTS_SCRIPTS
DOTS_TEMPLATES="${DOTS_TEMPLATES:-"${DOTS_RES}/Templates"}" export DOTS_TEMPLATES
# pout_env "DOTS_FONTS"
# pout_env "DOTS_IMAGES"
# pout_env "DOTS_SCRIPTS"
# pout_env "DOTS_TEMPLATES"

#| User Directories
DOCUMENTS="${DOCUMENTS:-"${HOME}/Documents"}" export DOCUMENTS
DOWNLOADS="${DOWNLOADS:-"${HOME}/Downloads"}" export DOWNLOADS
MUSIC="${MUSIC:-"${HOME}/Music"}" export MUSIC
PHOTOS="${PHOTOS:-"${HOME}/Pictures"}" export PHOTOS
VIDEOS="${VIDEOS:-"${HOME}/Videos"}" export VIDEOS
WALLPAPERS="$(
  if [ -d "${PHOTOS}/Wallpapers" ]; then
    printf "%s" "${PHOTOS}/Wallpapers"
  elif [ -d "${HOME}/Pictures/wallpapers" ]; then
    printf "%s" "${HOME}/Pictures/wallpapers"
  else
    printf "%s" "${DOTS_RES}/Images/wallpaper"
  fi
)"
export WALLPAPERS
# pout_env "DOCUMENTS"
# pout_env "DOWNLOADS"
# pout_env "MUSIC"
# pout_env "PHOTOS"
# pout_env "VIDEOS"
# pout_env "WALLPAPERS"

#| System Directories
APPDATA="${APPDATA:-"${HOME}/AppData"}" export APPDATA

#| General
TIMESTAMP="$(date +%F_%H-%M-%S)"
DOTS_LOADED_APPS="${DOTS_LOG}/loaded_apps"
codeDOTS="${DOTS_CFG}/vscode/Dotfiles.code-workspace"
codeRUST="${DOTS_CFG}/vscode/Rust.code-workspace"
codeNIX="${DOTS_CFG}/vscode/Nix.code-workspace"
KEYMAPS="${DOTS_CFG}/utilities/sxhkd"
ASCII="${DOTS_RES}/Images/ascii"
