dictionaries = []
words = [
  "coreutils",
  "dotsrc",
  "direnv",
  "fastfetch",
  "posix",
  "jsonc",
  "rosé",
  "nixos",
  "starship",
  "thefuck",
  "treefmt",
  "wsl",
  "zoxide",
]
flag_words = []
ignore_paths = []
