{
  config,
  host,
  lib,
  lix,
  user,
  apps,
  keyboard,
  ...
}: let
  context = mkContext {
    inherit config;
    dom = "interface";
    sub = "managers";
    mod = "hyprland";
  };
  inherit (context) cfg ctx;

  inherit (lib.modules) mkIf mkMerge;
  inherit (lix.modules.construction) mkConfig mkContext;
  inherit (lix.options.construction) mkEnable mkOption;
  inherit (lix.types.primitives) bool;

  mkAddons = target:
    mkIf cfg.withAddons (import ./addons {
      inherit lib mkMerge;
      dmsEnabled = config.programs.dank-material-shell.enable or false;
    }).${target};

  # DMS 1.5/1.6 and Hyprland >= 0.55 use Lua as the native integration
  # contract. Keep this raw instead of passing the configuration through Home
  # Manager's generic settings serializer, which does not preserve DMS's Lua
  # module structure.
  hyprlandLua = ''
    -- Managed by Home Manager. Keep in sync with the DMS Hyprland Lua contract.
    hl.config({ autogenerated = false })

    -- DMS_STARTUP_BEGIN
    hl.on("hyprland.start", function()
      hl.exec_cmd("dbus-update-activation-environment --systemd --all")
      hl.exec_cmd("systemctl --user start hyprland-session.target")
      hl.exec_cmd("udiskie --automount --notify --smart-tray")
    end)
    -- DMS_STARTUP_END

    hl.env("XDG_CURRENT_DESKTOP", "Hyprland")

    hl.config({
      input = {
        kb_layout = "",
        kb_options = "${lib.optionalString keyboard.swapCapsEscape "caps:swapescape"}",
        numlock_by_default = true,
        follow_mouse = 0,
        accel_profile = "flat",
        touchpad = {
          tap_to_click = true,
          natural_scroll = false,
          scroll_factor = 0.3,
        },
      },
      general = {
        gaps_in = 5,
        gaps_out = 5,
        border_size = 2,
        layout = "dwindle",
      },
      decoration = {
        rounding = 12,
        active_opacity = 1.0,
        inactive_opacity = 1.0,
        shadow = {
          enabled = true,
          range = 30,
          render_power = 5,
          offset = "0 5",
          color = "rgba(00000070)",
        },
      },
      misc = {
        disable_hyprland_logo = true,
        disable_splash_rendering = true,
      },
      dwindle = {
        preserve_split = true,
      },
      master = {
        mfact = 0.5,
      },
    })

    hl.animation({ leaf = "windowsIn", enabled = true, speed = 3, bezier = "default" })
    hl.animation({ leaf = "windowsOut", enabled = true, speed = 3, bezier = "default" })
    hl.animation({ leaf = "workspaces", enabled = true, speed = 5, bezier = "default" })
    hl.animation({ leaf = "windowsMove", enabled = true, speed = 4, bezier = "default" })
    hl.animation({ leaf = "fade", enabled = true, speed = 3, bezier = "default" })
    hl.animation({ leaf = "border", enabled = true, speed = 3, bezier = "default" })

    hl.window_rule({ match = { class = "^(org\\.gnome\\.)" }, rounding = 12 })
    hl.window_rule({ match = { class = "^(gnome-control-center)$" }, tile = true })
    hl.window_rule({ match = { class = "^(pavucontrol)$" }, tile = true })
    hl.window_rule({ match = { class = "^(nm-connection-editor)$" }, tile = true })
    hl.window_rule({ match = { class = "^(org\\.gnome\\.Calculator)$" }, float = true })
    hl.window_rule({ match = { class = "^(gnome-calculator)$" }, float = true })
    hl.window_rule({ match = { class = "^(blueman-manager)$" }, float = true })
    hl.window_rule({ match = { class = "^(org\\.gnome\\.Nautilus)$" }, float = true })
    hl.window_rule({ match = { class = "^(xdg-desktop-portal)$" }, float = true })
    hl.layer_rule({ match = { namespace = "^(quickshell)$" }, no_anim = true })
    hl.layer_rule({ match = { namespace = "^dms:.*" }, no_anim = true })

    require("dms.colors")
    require("dms.outputs")
    require("dms.layout")
    require("dms.cursor")
    require("dms.binds")
    require("dms.binds-user")
    require("dms.windowrules")
  '';

  payload = {
    wayland.windowManager.hyprland = {
      enable = cfg.enable;
      configType = "lua";
      plugins = [];
      settings = {};
      extraConfig = hyprlandLua;

      # NixOS owns the Hyprland package and UWSM session. Home Manager's
      # Hyprland systemd integration creates a competing session target and
      # conflicts with programs.hyprland.withUWSM.
      package = null;
      systemd.enable = false;
    };

    # Home Manager enables portal integration for the Hyprland profile. Since
    # xdg-desktop-portal >= 1.17 requires an explicit backend selection, keep
    # the traditional first-compatible-backend behaviour at the Home layer;
    # NixOS owns the detailed Hyprland/GTK portal routing.
    xdg.portal.config.common.default = "*";

    programs = mkAddons "programs";
    services = mkAddons "services";

    # Home Manager creates/removes managed links in linkGeneration. Run the
    # compatibility cleanup afterwards so a stale hyprland.conf cannot win
    # Hyprland's config discovery over the native Lua entrypoint.
    home.activation.removeLegacyHyprlandConf = lib.hm.dag.entryAfter ["linkGeneration"] ''
      legacy="$HOME/.config/hypr/hyprland.conf"
      if [ -e "$legacy" ] || [ -L "$legacy" ]; then
        rm -f "$legacy"
      fi
    '';

    # Old user-local portal descriptors shadow the NixOS-owned descriptors in
    # /run/current-system/sw/share/xdg-desktop-portal/portals. Remove only the
    # known stale copies; the system packages remain the source of truth.
    home.activation.removeLegacyUserPortalDescriptors = lib.hm.dag.entryAfter ["linkGeneration"] ''
      portal_dir="$HOME/.local/share/xdg-desktop-portal/portals"
      for portal in gtk.portal darkman.portal; do
        path="$portal_dir/$portal"
        if [ -e "$path" ] || [ -L "$path" ]; then
          rm -f "$path"
        fi
      done
    '';

    # DMS expects Lua output fragments in 1.5/1.6. Use a regular file rather
    # than a Home Manager store symlink because DMS may reload this fragment at
    # runtime. Home Manager remains the source of truth for the initial layout.
    home.activation.normalizeDmsHyprlandOutputs = lib.hm.dag.entryAfter ["linkGeneration"] ''
      dms_dir="$HOME/.config/hypr/dms"
      outputs="$dms_dir/outputs.lua"
      mkdir -p "$dms_dir"
      rm -f "$dms_dir/outputs.conf"
      cat > "$outputs" <<'EOF_DMS_OUTPUTS'
      -- Managed by Home Manager; DMS-compatible Hyprland 0.55+ Lua.
      hl.monitor({ output = "eDP-1", mode = "1920x1080@144", position = "0x0", scale = 1 })
      hl.monitor({ output = "HDMI-A-1", mode = "1920x1080@100", position = "0x1080", scale = 1 })
      EOF_DMS_OUTPUTS
    '';
  };
in
  mkConfig {
    inherit context;
    options = {
      enable = mkEnable ({inherit context;} // ctx.wantsHyprland);
      withAddons = mkOption {
        description = "Enable Hyprland addons";
        default = true;
        type = bool;
      };
      withRules = mkEnable {
        description = "Hyprland window rules";
      };
    };
    outputs = payload;
  }
