[global]
excludes = [
  "treefmt.toml",
  "generated.nix",
  "**/node_modules/**",
  "**/target/**",
  "**/dist/**",
  "**/.git/**",
]

#| Nix formatting
[formatter.nixfmt]
command = "nixfmt"
includes = ["*.nix"]
priority = 1

[formatter.alejandra]
command = "alejandra"
includes = ["*.nix"]
priority = 1

[formatter.deadnix]
command = "deadnix"
options = ["-e"]
includes = ["*.nix"]
priority = 2

[formatter.statix]
command = "statix"
options = ["check"]
includes = ["*.nix"]
priority = 3

#| Rust formatting
[formatter.rust]
command = "rustfmt"
includes = ["*.rs"]
options = ["--edition", "2021"]

#| Shell script formatting# Shell script formatting
[formatter.shellcheck]
command = "shellcheck"
includes = ["*.sh", "*.bash", ".bash*", "*.zsh", ".zsh*"]
options = ["-x", "-e", "SC1090,SC1091"]
priority = 2
fail_on_missing = false

[formatter.shfmt]
command = "shfmt"
includes = ["*.sh", "*.bash", ".bash*", "*.zsh", ".zsh*"]
options = ["-i", "2", "-ci", "-bn", "-sr", "-ln", "bash"]
fail_on_missing = false

#| Python formatting
[formatter.ruff]
command = "ruff"
includes = ["*.py"]
options = ["format", "--quiet"]

#| Data formats
[formatter.json]
command = "jq"
includes = ["*.json", "*.jsonc"]
options = ["--indent", "2", "--sort-keys", "-M"]

[formatter.toml]
command = "taplo"
includes = ["*.toml"]
options = ["fmt"]

#| Documentation
[formatter.markdown]
command = "markdownlint"
includes = ["*.md"]
options = ["--fix", "--config", ".markdownlint.json"]

#| Lua formatting
[formatter.stylua]
command = "stylua"
includes = ["*.lua"]

#| YAML formatting
[formatter.yamlfmt]
command = "yamlfmt"
includes = ["*.yaml", "*.yml"]
