[global]
excludes = [
  # "treefmt.toml",
  "generated.nix",
  "**/node_modules/**",
  "**/target/**",
  "**/dist/**",
  "**/.git/**",
  "**/review/**",
  # "**/qbittorrent/**",  #TODO Temporary
  # "Assets/**",          #TODO Temporary
  # "Configuration/**",   #TODO Temporary
  # "Environment/**",     #TODO Temporary
  # "Bin/**",             #TODO Temporary
  # "Documentation/**",   #TODO Temporary
]

# #| Documentation
# [formatter.markdown]
# command = "markdownlint"
# includes = ["*.md"]
# options = ["--fix", "--config", ".markdownlint.json"]
# priority = 1

# [formatter.mdsh]
# command = "mdsh"
# excludes = []
# includes = ["README.md"]
# options = ["--inputs"]
# priority = 2

# [formatter.texfmt]
# command = "tex-fmt"
# excludes = []
# includes = ["*.tex", "*.sty", "*.cls", "*.bib", "*.cmh"]
# options = []

# [formatter.typstfmt]
# command = "typstfmt"
# excludes = []
# includes = ["*.typ", "*.typst"]
# options = []
# priority = 1

# [formatter.typstyle]
# command = "typstyle"
# excludes = []
# includes = ["*.typ", "*.typst"]
# options = ["-i"]
# priority = 2

#TODO: Not working
# [formatter.editorconfig]
# command = "fmt_editorconfig"
# includes = [".editorconfig"]
# options = ["--format"]

# [formatter.editorconfig_lint]
# command = "fmt_editorconfig"
# includes = [".editorconfig"]
# options = ["--lint"]

#| Nix formatting
[formatter.alejandra]
command  = "alejandra"
includes = ["*.nix"]
priority = 1
# fail_on_error = true

# # # [formatter.nixfmt]
# # # command = "nixfmt"
# # # includes = ["*.nix"]
# # # priority = 1

# # [formatter.deadnix]
# # command = "deadnix"
# # excludes = []
# # includes = ["*.nix"]
# # options = ["--edit"]
# # priority = 2

# # [formatter.statix]
# # command = "statix"
# # options = ["fix"]
# # includes = ["*.nix"]
# # priority = 3

# # #| Rust formatting
# [formatter.rust]
# command  = "rustfmt"
# options  = ["--edition", "2021"]
# includes = ["*.rs"]
# priority = 1

# [formatter.leptosfmt]
# command  = "leptosfmt"
# includes = ["*.rs"]
# priority = 2

# #| Shell script formatting# Shell script formatting
# [formatter.shellcheck]
# command  = "shellcheck"
# options  = ["--check-sourced", "--shell=sh", "*.bash", ".bash*"]
# includes = ["*.sh", ".dotsrc", ".env*", ".shellcheckrc"]
# priority = 1

# [formatter.shfmt]
# command = "shfmt"
# includes = ["*.sh", ".dotsrc", ".env*", ".shellcheckrc", "*.bash", ".bash*"]
# options = [
#   "--apply-ignore",
#   "--binary-next-line",
#   "--space-redirects",
#   "--case-indent",
#   "--diff",
#   "--posix",
#   "--write",
# ]
# priority = 2

# [formatter.fish]
# command  = "fish_indent"
# includes = ["*.fish"]
# options  = ["--write"]

# [formatter.justfile]
# command  = "just"
# includes = [".justfile"]
# options  = ["--unstable", "--fmt", "--justfile"]

# #| Python formatting
# [formatter.ruff]
# command  = "ruff"
# includes = ["*.py"]
# options  = ["format", "--quiet"]

# #| Data formats
# [formatter.biome]
# command = "biome"
# includes = [

#   "*.ts",
#   "*.mts",
#   "*.cts",
#   "*.js",
#   "*.cjs",
#   "*.mjs",
#   "*.jsx",
#   "*.tsx",
#   "*.d.ts",
#   "*.d.mts",
#   "*.d.cts",
#   "*.vue",
#   "*.html",
#   "*.css",
#   "*.json",
#   "*.jsonc",
#   "*.astro",
#   "*.svelte",
#   "*.graphql",
#   "*.webmanifest",
# ]
# options = ["format", "ci"]
# priority = 1

# [formatter.json]
# command  = "jq"
# includes = ["*.json", "*.jsonc"]
# options  = ["--indent", "2", "--sort-keys", "-M"]
# priority = 2

# #| TOML
# [formatter.toml]
# command  = "taplo"
# includes = ["*.toml"]
# options  = ["format"]

# #| Lua formatting
# [formatter.stylua]
# command  = "stylua"
# includes = ["*.lua"]

# #| YAML formatting
# [formatter.yamlfmt]
# command  = "yamlfmt"
# includes = ["*.yaml", "*.yml"]
# options  = ["-formatter", "retain_line_breaks=true"]

# [formatter.actionlint]
# command = "actionlint"
# excludes = []
# includes = [".github/workflows/*.yml", ".github/workflows/*.yaml"]
# options = []

# [formatter.asmfmt]
# command = "asmfmt"
# options = ["-w"]
# includes = ["*.s"]

# [formatter.beautysh]
# command = "beautysh"
# excludes = []
# includes = ["*.sh", "*.bash", ".bash*", "*.zsh", ".zsh*"]
# options = ["-i", "2"]

# [formatter.buildifier]
# command = "buildifier"
# excludes = []
# includes = ["*.bazel", "*.bzl"]
# options = []

# [formatter.cabal-fmt]
# command = "cabal-fmt"
# excludes = []
# includes = ["*.cabal"]
# options = ["--inplace"]

# [formatter.clang-format]
# command = "clang-format"
# excludes = []
# includes = ["*.c", "*.cc", "*.cpp", "*.h", "*.hh", "*.hpp"]
# options = ["-i"]

# [formatter.cljfmt]
# command = "cljfmt"
# excludes = []
# includes = ["*.clj", "*.cljc", "*.cljs", "*.cljx"]
# options = ["fix"]

# [formatter.cmake-format]
# command = "cmake-format"
# excludes = []
# includes = ["*.cmake", "CMakeLists.txt"]
# options = ["--in-place"]

# [formatter.dart-format]
# command = "dart"
# excludes = []
# includes = ["*.dart"]
# options = ["format"]

# [formatter.deno]
# command = "deno"
# excludes = []
# includes = [
#   "*.css",
#   "*.html",
#   "*.js",
#   "*.json",
#   "*.jsonc",
#   "*.jsx",
#   "*.less",
#   "*.markdown",
#   "*.md",
#   "*.sass",
#   "*.scss",
#   "*.ts",
#   "*.tsx",
#   "*.yaml",
#   "*.yml",
# ]
# options = ["fmt"]

# [formatter.dos2unix]
# command = "dos2unix"
# excludes = []
# includes = ["*"]
# options = ["--keepdate"]

# [formatter.fish_indent]
# command = "fish_indent-wrapper"
# excludes = []
# includes = ["*.fish"]
# options = []

# [formatter.keep-sorted]
# command = "keep-sorted"
# excludes = []
# includes = ["*"]
# options = []

# [formatter.nufmt]
# command = "nufmt"
# excludes = []
# includes = ["*.nu"]
# options = []

# #| Ruby
# [formatter.rufo]
# command = "rufo"
# options = ["-x"]
# includes = ["*.rb"]
# priority = 1

# [formatter.rubocop]
# command = "rubocop"
# excludes = []
# includes = ["*.rb"]
# options = []
# priority = 2

# #| SQL
# [formatter.sqruff]
# command = "sqruff"
# excludes = []
# includes = ["*.sql"]
# options = ["fix", "--force"]

# [formatter.terraform]
# command = "tofu"
# excludes = []
# includes = ["*.tf", "*.tfvars", "*.tftest.hcl"]
# options = ["fmt"]

# [formatter.typos]
# command = "typos"
# excludes = []
# includes = ["*"]
# options = ["--diff"]
# # options = ["--write-changes"]

# [formatter.zig]
# command = "zig"
# excludes = []
# includes = ["*.zig", "*.zon"]
# options = ["fmt"]
