#!/usr/bin/env bash
set -euo pipefail

source "@scripts@/app"

main() {
  local cfg_dir="$(app_cfg mpd)"
  local music_dir="$(app_dir MUSIC)"

  mkdir -p "$cfg_dir/playlists" "$music_dir"

  exec "@cmd@" --no-daemon "${cfg_dir}/mpd.conf" "$@"
}

main "$@"
