#!/usr/bin/env bash

main() {
  set_defaults
  parse_arguments "$@"
  execute_command
}

set_defaults() {
  URL=""
  FMT="@format@"
  DIR="${MEDIA_DOWNLOADS:-@downloads@}"
  CFG="${MEDIA_CFG_YTD:-@config@}/yt-dlp.conf"
  CMD="@command@"
}

usage() {
  case "$1" in
    --option)
      printf "Error: %s requires an argument\n" "$2"
      ;;
    *)
      printf "Usage: yt-download <url> [quality]\n"
      printf "Quality options: best, 1080p, 720p, 480p, audio\n"
      ;;
  esac
  exit 1
}

parse_arguments() {
  while [ "$#" -gt 0 ]; do
    case "$1" in
      -u|--url)
        [ -n "$2" ] || usage --option "$1"
        shift
        URL="$1"
        ;;
      -f|--format)
        [ -n "$2" ] || usage --option "$1"
        shift
        FMT="$1"
        ;;
      -d|--dir)
        [ -n "$2" ] || usage --option "$1"
        shift
        DIR="$1"
        ;;
      -c|--config)
        [ -n "$2" ] || usage --option "$1"
        shift
        CFG="$1"
        ;;
      *)
        URL="$1"
        ;;
    esac
    shift
  done

  [ -n "$URL" ] || usage >&2
}

execute_command() {
  mkdir -p "$DIR" "$(dirname "$CFG")"

  case "$FMT" in
    best)
      "$CMD" --config-location "$CFG" "$URL"
      ;;
    audio)
      "$CMD" --config-location "$CFG" --extract-audio --audio-format mp3 "$URL"
      ;;
    *)
      "$CMD" \
        --config-location "$CFG" \
        --format "bestvideo[height<=${FMT%p}]+bestaudio/best[height<=${FMT%p}]" \
        --output "${DIR}/%(title)s.%(ext)s" \
        "$URL"
      ;;
  esac
}

main "$@"
