# theme = "catppuccin_macchiato"
# theme = "catppuccin_mocha"
# theme = "catppuccin_frappe"
# theme = "catppuccin_latte"
# theme = "kanagawa"
# theme = "noctis"
# theme = "noctis_bordo"
# theme = "monokai_pro_machine"
# theme = "monokai_pro_octagon"
# theme = "monokai_pro_spectrum"
# theme = "monokai_pro_ristretto"
# theme = "monokai_pro_spectrum"
theme = "rose_pine_moon"
# theme = "tokyonight_storm"

[editor]
auto-format  = true
auto-save    = true
bufferline   = "never"    # "multiple"
color-modes  = true
cursorline   = true
idle-timeout = 50
line-number  = "relative"
mouse        = true

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]
hidden  = false
parents = false

[editor.indent-guides]
character   = "╎"  # Some characters that work well: "▏", "╎", "┆", "┊", "⸽"
render      = true
skip-levels = 1

[editor.lsp]
auto-signature-help         = true
display-inlay-hints         = true
display-messages            = true
display-signature-help-docs = true
snippets                    = true

[editor.statusline]
center = ["file-name"]
left = ["mode", "spinner", "spacer", "file-modification-indicator"]
right = [
  "diagnostics",
  "version-control",
  "selections",
  "position",
  "file-encoding",
  "file-line-ending",
  "file-type",
]
separator = "│"

[editor.statusline.mode]
insert = "INSERT"
normal = "NORMAL"
select = "SELECT"

[editor.whitespace]
# render = "all"


[editor.whitespace.characters]
nbsp  = "⍽"
space = " "
tab   = "→"
# newline = "⏎"
tabpad = "·" # Tabs will look like "→···" (depending on tab width)

# At most one section each of 'keys.normal', 'keys.insert' and 'keys.select'
[keys.normal]
"C-]" = "indent"

esc = ["collapse_selection", "keep_primary_selection"]
# tab = ["collapse_selection", "keep_primary_selection"]
"C-S-esc" = "extend_line"                 # Maps Ctrl-Shift-Escape to extend_line
C-S-o     = ":config-open"                # Maps the Ctrl-o to opening of the helix config file
C-S-r     = ":config-reload"              # Maps the Ctrl-o to opening of the helix config file
C-s       = ":w"                          # Maps the Ctrl-s to the typable command :w which is an alias for :write (save file)
a         = "move_char_left"              # Maps the 'a' key to the move_char_left command
"ret"     = ["open_below", "normal_mode"]
w         = "move_line_up"                # Maps the 'w' key move_line_up

[keys.normal.space]
# s = ":write"
# m = ":format"
# q = ":quit!"
# r = ":config-reload"
# o = ":config-open"

[keys.normal.g]
a = ":format"

[keys.insert]
"A-x" = "normal_mode"         # Maps Alt-X to enter normal mode
j     = { k = "normal_mode" } # Maps `jk` to exit insert mode
