use-grammars = { only = [
  "rust",
  "html",
  "css",
  "sql",
  "python",
  "bash",
  "make",
  "toml",
  "json",
  "json5",
  "yaml",
  "markdown",
  "awk",
  "nu",
  "nix",
] }

# [[languages]]
# name = "rust"

[language-server.rust-analyzer.config]
cargo     = { buildScripts = { enable = true }, features = "all" }
check     = { features = "all" }
procMacro = { enable = true }

[language-server.rust-analyzer.config.inlayHints]
chainingHints        = { enable = false }
lifetimeElisionHints = { enable = false, useParameterNames = false }
parameterHints       = { enable = false }
renderColons         = false
typeHints            = { hideNamedConstructor = true, hideClosureInitialization = true }

[language-server.tailwind-ls]
args    = ["--stdio"]
command = "tailwindcss-language-server"

[language-server.tailwind-ls.config]
tailwindCSS = { experimental = { classRegex = ["class=\"(.*)\""] } }

[[language]]
language-servers = ["rust-analyzer", "tailwind-ls"]
name             = "rust"

[[language]]
language-servers = ["vscode-css-language-server", "tailwind-ls"]
name             = "css"

[[language]]
language-servers = ["vscode-html-language-server", "tailwind-ls"]
name             = "html"
