[[language]]
  name = "nix"
  auto-format = true
  language-servers = ["nixd"]

  [language.formatter]
    command = "alejandra"

[[language]]
  name = "bash"
  auto-format = true

  [language.formatter]
    command = "shfmt"
    args = [
      "--apply-ignore",
      "--binary-next-line",
      "--space-redirects",
      "--case-indent",
      "--indent",
      "2",
    ]

  [language.indent]
    tab-width = 2
    unit = "\t"

[[language]]
  name = "rust"
  auto-format = true
  language-servers = ["rust-analyzer"]

  [language.formatter]
    command = "rustfmt"

[[language]]
  name = "python"
  auto-format = true

  [language.formatter]
    command = "ruff"
    args = ["format", "-"]

[[language]]
  name = "toml"
  auto-format = true

  [language.formatter]
    command = "tombi"
    args = ["format", "-"]

[[language]]
  name = "zig"
  auto-format = true

  [language.formatter]
    command = "zig"
    args = ["fmt", "--stdin", "--stdout"]

[[language]]
  name = "typst"
  auto-format = true

  [language.formatter]
    command = "typstyle"
    args = ["format", "-"]

[[language]]
  name = "lua"
  auto-format = true

  [language.formatter]
    command = "stylua"
    args = ["-"]

[[language]]
  name = "yaml"
  auto-format = true

  [language.formatter]
    command = "yamlfmt"

[[language]]
  name = "javascript"
  auto-format = true

  [language.formatter]
    command = "biome"
    args = ["format", "--stdin-file-path", "file.js"]

[[language]]
  name = "typescript"
  auto-format = true

  [language.formatter]
    command = "biome"
    args = ["format", "--stdin-file-path", "file.ts"]

[[language]]
  name = "tsx"
  auto-format = true

  [language.formatter]
    command = "biome"
    args = ["format", "--stdin-file-path", "file.tsx"]

[[language]]
  name = "jsx"
  auto-format = true

  [language.formatter]
    command = "biome"
    args = ["format", "--stdin-file-path", "file.jsx"]

[[language]]
  name = "json"
  auto-format = true

  [language.formatter]
    command = "biome"
    args = ["format", "--stdin-file-path", "file.json"]

[[language]]
  name = "markdown"
  auto-format = true

  [language.formatter]
    command = "rumdl"
    args = ["fmt", "-"]
