[battery]
  charging_symbol = "⇡ "
  discharging_symbol = "⇣ "
  empty_symbol = "❗ "
  full_symbol = "• "
  unknown_symbol = "❓ "

[erlang]
  symbol = "ⓔ "

[nodejs]
  symbol = "[⬢](bold green) "

[pulumi]
  symbol = "🧊 "
