# https://numtide.github.io/devshell
[[commands]]
package = "treefmt2"

[[commands]]
package = "eza"

[[commands]]
package = "bat"

[[commands]]
package = "vscodium-fhs"
name = "codium"
help= "Visual Studio Code without telemetry and easy usage of extensions without nix-specific modifications."

[[commands]]
package = "fd"

[[commands]]
package = "btop"

[[commands]]
package = "ripgrep"
name = "rg"

[[commands]]
package = "yazi"

[[commands]]
package = "neovim"
name = "nvim"

[[commands]]
package = "cowsay"

[[commands]]
package = "fend"

[[commands]]
package = "fastfetch"

[[commands]]
package = "lesspipe"

[[commands]]
package = "rust-script"

[[commands]]
package = "just"

[[commands]]
package = "powershell"

[[commands]]
package = "bashInteractive"

[[commands]]
package = "glib"

[[commands]]
package = "treefmt2"

[[commands]]
package = "getoptions"

[[commands]]
package = "pre-commit"

[[commands]]
package = "fd"

[[commands]]
package = "btop"

[[commands]]
package = "fzf"

[[commands]]
package = "lsd"

[[commands]]
package = "delta"

[[commands]]
package = "yazi"

[[commands]]
package = "tlrc"
name = "tldr"

[[commands]]
package = "tokei"

[[commands]]
package = "thefuck"

[[commands]]
package = "zoxide"

[[commands]]
package = "neovim"

[[commands]]
package = "helix"
name = "hx"

[[commands]]
package = "direnv"

[[env]]
name = "CRAOLE"
value = "on"

# https://numtide.github.io/devshell

[devshell]
packages = [
  "getoptions",
  "pre-commit",
  "eza",
  "bat",
  "fd",
  "btop",
  "ripgrep",
  "fzf",
  "lsd",
  "delta",
  "yazi",
  "tlrc",
  "tokei",
  "thefuck",
  "zoxide",
  "neovim",
  "helix",
  "direnv",
  "fend",
  "fastfetch",
  "lesspipe",
  "rust-script",
  "just",
  "powershell",
  "bashInteractive",
  "glib",
  "treefmt2",

  #| Image Tools
  "viu",
  "imv",
  "sxiv",

  #| Languages Tools and Formatters
  "coreutils-prefixed",
  # php

  #| Nix
  "nixfmt-rfc-style",
  "nixd",
  "deadnix",

  #| JavaScript/TypeScript
  "biome",                        # Formatter, linter, and more
  "nodePackages_latest.prettier", # Formatter
  "prettierd",                    # Formatter daemon
  "pnpm",

  #| Rust
  "rustup",
  # "rustfmt",   # Formatter
  "leptosfmt",

  #| Python
  # python314
  "ruff",

  #| Shell
  "shfmt",
  "shellcheck",

  #| SQL
  # sqlfluff # Formatter/linter

  #| Configuration
  "taplo",   # Toml Formatter
  "stylua",  # Lua Formatter
  "yamlfmt", # YamlFormatter

  # Typst
  "typst",
  "typstfmt", # Formatter
  "typstyle", # Linter
]
