# https://numtide.github.io/devshell


[[commands]]
name = "rebuild"
category = "System Management"
command = "sudo nixos-rebuild --flake $DOTS switch $@"
help = "rebuild current NixOS"

[[commands]]
category = "Interactive Shell"
name = "bash"
package = "bashInteractive"

[[commands]]
category = "Integrated Development Environment"
name = "codium"
package = "vscodium-fhs"
help = "Visual Studio Code wrapper without telemetry or nix-specific restrictions."

[[commands]]
category = "Version Control Tools"
package = "delta"

[[commands]]
category = "Utilities"
package = "fend"

[[commands]]
category = "Version Control Tools"
package = "hci"

[[commands]]
category = "Integrated Development Environment"
name = "hx"
package = "helix"

[[commands]]
category = "Integrated Development Environment"
name = "nvim"
command = "nix run github:nix-community/neovim-nightly-overlay"
package = "neovim"

[[commands]]
category = "Package Managers"
package = "pnpm"

[[commands]]
category = "Interactive Shell"
name = "pwsh"
package = "powershell"

[[commands]]
category = "Version Control Tools"
package = "pre-commit"

[[commands]]
category = "Utilities"
package = "rust-script"

[[commands]]
category="Information Tools"
package = "tldr"

[[commands]]
category="Information Tools"
package = "tokei"

[[commands]]
category="Linters/Formatters"
package = "treefmt2"

[[env]]
name = "CRAOLE"
value = "on"

[devshell]
packages = [
  "getoptions",
  "pre-commit",
  "eza",
  "bat",
  "fd",
  "btop",
  "jq",
  "ripgrep",
  "fzf",
  "lsd",
  "delta",
  "yazi",
  "tldr",
  "tokei",
  "thefuck",
  "zoxide",
  "helix",
  "direnv",
  "fend",
  "fastfetch",
  "lesspipe",
  "rust-script",
  "just",
  "powershell",
  "bashInteractive",
  "glib",
  "treefmt2",

  #| Languages Tools and Formatters
  "coreutils-prefixed",
  # php

  #| Nix
  "nixfmt-rfc-style",
  "nixd",
  "deadnix",

  #| JavaScript/TypeScript
  "biome",                        # Formatter, linter, and more
  "nodePackages_latest.prettier", # Formatter
  "prettierd",                    # Formatter daemon
  "pnpm",

  #| Rust
  "rustup",
  # "rustfmt",   # Formatter
  "leptosfmt",

  #| Python
  # python314
  "ruff",

  #| Shell
  "shfmt",
  "shellcheck",

  #| SQL
  # sqlfluff # Formatter/linter

  #| Configuration
  "taplo",   # Toml Formatter
  "stylua",  # Lua Formatter
  "yamlfmt", # YamlFormatter

  # Typst
  "typst",
  "typstfmt", # Formatter
  "typstyle", # Linters
]
