# https://numtide.github.io/devshell
[[commands]]
package = "hello"

[devshell]
packages = [
  "vscodium-fhs",
  "getoptions",
  "pre-commit",
  "eza",
  "bat",
  "fd",
  "btop",
  "ripgrep",
  "fzf",
  "lsd",
  "delta",
  "yazi",
  "tlrc",
  "tokei",
  "thefuck",
  "zoxide",
  "tldr",
  "neovim",
  "helix",
  "direnv",
  "fend",
  "fastfetch",
  "lesspipe",
  "rust-script",
  "just",
  "powershell",
  "bashInteractive",
  "glib",
  "treefmt2",

  #| Image Tools
  "viu",
  "imv",
  "sxiv",

  #| Languages Tools and Formatters
  "coreutils-prefixed",
  # php

  #| Nix
  "nixfmt-rfc-style",
  "nixd",
  "deadnix",

  #| JavaScript/TypeScript
  "biome",                        # Formatter, linter, and more
  "nodePackages_latest.prettier", # Formatter
  "prettierd",                    # Formatter daemon
  "pnpm",

  #| Rust
  "rustup",
  "rustfmt",   # Formatter
  "leptosfmt",

  #| Python
  # python314
  "ruff",

  #| Shell
  "shfmt",
  "shellcheck",

  #| SQL
  # sqlfluff # Formatter/linter

  #| Configuration
  "taplo",   # Toml Formatter
  "stylua",  # Lua Formatter
  "yamlfmt", # YamlFormatter

  # Typst
  "typst",
  "typstfmt", # Formatter
  "typstyle", # Linter
]
