#!/bin/sh
#shellcheck enable=all
set -eu

: "${HINDSIGHT_SECRETS_FILE:?HINDSIGHT_SECRETS_FILE not set}"
: "${HINDSIGHT_COMPOSE_FILE:?HINDSIGHT_COMPOSE_FILE not set}"
: "${HINDSIGHT_COMPOSE_PROJECT:?HINDSIGHT_COMPOSE_PROJECT not set}"
: "${HINDSIGHT_CONTAINER_RUNTIME:?HINDSIGHT_CONTAINER_RUNTIME not set}"

if [ -r "${HINDSIGHT_SECRETS_FILE}" ]; then
  # shellcheck disable=SC1090
  . "${HINDSIGHT_SECRETS_FILE}"
fi

case "${HINDSIGHT_LLM_BACKEND:-openrouter}" in
openrouter)
  HINDSIGHT_API_LLM_API_KEY="${OPENROUTER_API_KEY:-${HINDSIGHT_OPENROUTER_API_KEY:-}}"
  ;;
groq)
  HINDSIGHT_API_LLM_API_KEY="${GROQ_API_KEY:-${HINDSIGHT_GROQ_API_KEY:-}}"
  ;;
*)
  HINDSIGHT_API_LLM_API_KEY="${HINDSIGHT_API_LLM_API_KEY:-}"
  ;;
esac
export HINDSIGHT_API_LLM_API_KEY

"${HINDSIGHT_CONTAINER_RUNTIME}" compose \
  -p "${HINDSIGHT_COMPOSE_PROJECT}" \
  -f "${HINDSIGHT_COMPOSE_FILE}" down
