#!/bin/sh
#shellcheck enable=all
set -eu

: "${HINDSIGHT_CONTAINER_NAME:?HINDSIGHT_CONTAINER_NAME not set}"
: "${HINDSIGHT_CONTAINER_RUNTIME:?HINDSIGHT_CONTAINER_RUNTIME not set}"

exec "${HINDSIGHT_CONTAINER_RUNTIME}" logs -f "${HINDSIGHT_CONTAINER_NAME}"
