#!/usr/bin/env python3
"""Generate toolchain adapters from .config/toolchain.toml."""
from __future__ import annotations

import argparse
import pathlib
import sys
import tomllib

HEADER = "# Generated by scripts/sync_toolchain.py; do not edit.\n"


def load_source(root: pathlib.Path) -> dict[str, object]:
    path = root / ".config" / "toolchain.toml"
    with path.open("rb") as stream:
        source = tomllib.load(stream)
    if source.get("schema") != 1:
        raise ValueError(f"unsupported toolchain schema in {path}")
    tools = source.get("tools")
    if not isinstance(tools, dict) or not tools:
        raise ValueError(f"[tools] must contain at least one tool in {path}")
    if any(not isinstance(name, str) or not isinstance(version, str) for name, version in tools.items()):
        raise ValueError("tool names and versions must be strings")
    return tools


def render_rust_toolchain(tools: dict[str, object]) -> str:
    rust = tools.get("rust")
    if rust is None:
        return HEADER
    return f'{HEADER}[toolchain]\nchannel = "{rust}"\n'


def render_mise(tools: dict[str, object]) -> str:
    lines = [HEADER.rstrip("\n"), "[tools]"]
    lines.extend(f'{name} = "{tools[name]}"' for name in sorted(tools))
    lines.append("")
    return "\n".join(lines)


def generated(root: pathlib.Path) -> dict[pathlib.Path, str]:
    tools = load_source(root)
    outputs = {
        root / ".config" / "mise.toml": render_mise(tools),
    }
    if "rust" in tools:
        outputs[root / "rust-toolchain.toml"] = render_rust_toolchain(tools)
    return outputs


def sync(root: pathlib.Path) -> None:
    for path, content in generated(root).items():
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(content)


def check(root: pathlib.Path) -> bool:
    return all(path.is_file() and path.read_text() == content for path, content in generated(root).items())


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--root", type=pathlib.Path, default=pathlib.Path.cwd())
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    try:
        if args.check:
            if not check(args.root):
                print("Generated toolchain adapters are stale; run scripts/sync_toolchain.py", file=sys.stderr)
                return 1
        else:
            sync(args.root)
    except (OSError, tomllib.TOMLDecodeError, ValueError) as error:
        print(error, file=sys.stderr)
        return 2
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
