mode    = "project" # "aware" or "project"
project = ""

[shell]
args = ["--login"]
name = "bash"


[dirs]
cache   = "C:\\Users\\Administrator\\AppData\\Local\\hatch\\Cache"
data    = "C:\\Users\\Administrator\\AppData\\Local\\hatch"
project = []
python  = "isolated"

[dirs.env]
virtual = ".hatch"

[projects]

[publish.index]
repo = "main"

[template]
email = "craole@tuta.io"
name  = "Craig 'Craole' Cole"

[template.licenses]
default = ["MIT"]
headers = true

[template.plugins.default]
ci         = false
src-layout = true
tests      = true

[terminal.styles]
debug   = "bold"
error   = "bold red"
info    = "bold"
spinner = "simpleDotsScrolling"
success = "bold cyan"
waiting = "bold magenta"
warning = "bold yellow"
