# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  modulesPath,
  ...
}: let
  inherit (lib.modules) mkDefault;
in {
  imports = [(modulesPath + "/installer/scan/not-detected.nix")];

  boot.initrd.availableKernelModules = [
    "xhci_pci"
    "ehci_pci"
    "ata_piix"
    "usbhid"
    "usb_storage"
    "sd_mod"
    "sr_mod"
    "sdhci_pci"
  ];
  boot.initrd.kernelModules = [];
  boot.kernelModules = ["kvm-intel"];
  boot.extraModulePackages = [];

  fileSystems = {
    "/" = {
      device = "/dev/disk/by-uuid/00261c80-742a-4f12-8b52-c0733b0c1cf9";
      fsType = "btrfs";
    };

    "/home" = {
      device = "/dev/disk/by-uuid/00261c80-742a-4f12-8b52-c0733b0c1cf9";
      fsType = "btrfs";
      options = ["subvol=home"];
    };

    "/nix" = {
      device = "/dev/disk/by-uuid/00261c80-742a-4f12-8b52-c0733b0c1cf9";
      fsType = "btrfs";
      options = ["subvol=nix"];
    };
  };

  swapDevices = [
    {device = "/dev/disk/by-uuid/398f5949-025d-4f93-91e8-e072f7b88896";}
  ];

  nixpkgs = {
    hostPlatform = mkDefault "x86_64-linux";
  };
  hardware = {
    bluetooth = {
      enable = true;
      powerOnBoot = true;
    };
    cpu.intel.updateMicrocode = mkDefault config.hardware.enableRedistributableFirmware;
  };
}
