#!/bin/sh

CMD_JUST="${CMD_JUST:-"$(command -v just 2>/dev/null)"}"
CMD_TREEFMT="${CMD_TREEFMT:-"$(command -v treefmt 2>/dev/null)"}"
CMD_FD="${CMD_FD:-"$(command -v fd 2>/dev/null)"}"

[ -x "${CMD_JUST}" ] &&
  if [ -x "${CMD_FD}" ]; then
    fd --hidden --glob "*justfile" |
      while read -r file; do
        "${CMD_JUST}" --fmt --unstable --justfile "${file}" ||
          printf "[ERROR]>-> Failed to format %s\n" "${file}"
      done
  else
    find . -name "justfile" -o -name "*.justfile" -o -name ".justfile" |
      while read -r file; do
        "${CMD_JUST}" --fmt --unstable --justfile "${file}" ||
          printf "[ERROR]>-> Failed to format %s\n" "${file}"
      done
  fi

[ -x "${CMD_TREEFMT}" ] &&
  if
    ! "${CMD_TREEFMT}" --allow-missing-formatter --clear-cache --fail-on-change
  then
    printf "[WARN]>-> treefmt completed with changes/errors\n"
    exit 1
  fi
