#!/bin/sh

for file in "$@"; do
  shellcheck "${file}"
  shfmt \
    --apply-ignore \
    --binary-next-line \
    --space-redirects \
    --case-indent \
    --indent 2 \
    --write \
    "${file}"
done
