# https://numtide.github.io/devshell

[[commands]]
category = "Media Management"
package = "curseradio"
help = "Terminal-based internet radio player"

[[commands]]
category = "Media Management"
package = "freetube"

[[commands]]
category = "Media Management"
package = "firefox-devedition-bin"
help = "Mozilla Firefox Developer Edition"

[[commands]]
category = "Media Management"
package = "mpd"

[[commands]]
category = "Media Management"
name = "mpv"
package = "mpv"
help = "General-purpose media player"

[[commands]]
category = "Media Management"
package = "ncmpcpp"
help = "NCurses MPD Client with a modern look and feel"

[[commands]]
category = "Media Management"
package = "playerctl"
# help = "Control media players from the command line"

[[commands]]
category = "Media Management"
package = "shortwave"

[[commands]]
category = "Media Management"
package = "strawberry"

[[commands]]
category = "Media Management"
package = "viu"
help = "Terminal-based image viewer"

[devshell]
packages = [
  #| Shell & Productivity
  "eza",
  "bat",
  "fd",
  "ripgrep",
  "yazi",
  "glib",

  #| Image Tools
  "viu",
  "imv",
  "sxiv",
  "feh",
  "swww",
  "imagemagick", # Gor advanced image processing

  #| Music & Audio
  "ncmpcpp",
  "mpc-cli",
  "mpd",
  "curseradio",
  "playerctl",
  "pamixer",
  "shortwave",
  "strawberry",
  "libnotify",  # For notifications in media players

  #| Development Tools
  "btop",
  "ffmpeg",
  "curl",
  "fastfetch",
  "fzf",
  "jq",
  "rlwrap",
  "socat",
  "xclip",     # Clipboard utility
  "yt-dlp",    # For downloading videos
  "mediainfo", # Media info tool

  #| Additional Tools
  "xsel",        # Alternative clipboard tool
  "imagemagick", # For image manipulation
]

# Optional: Add service configurations if needed
# Example for MPD:
# [[services]]
# name = "mpd"
# enable = true
# start = true
