#!/usr/bin/env bash
set -euo pipefail

main() {
  # shellcheck disable=SC2124
  local cfg_dir="${@cfgVar@:?@cfgVar@ is not set}"
  # shellcheck disable=SC2124
  local music_dir="${@musicVar@:?@musicVar@ is not set}"

  mkdir -p "${cfg_dir}/playlists" "${music_dir}"

  "@cmd@" --no-daemon "${cfg_dir}/mpd.conf" "$@"
}

main "$@"
