#!/usr/bin/env bash
set -euo pipefail

main() {
  local cfg_dir="${APP_CFG_MPD:?APP_CFG_MPD is not set}"
  local music_dir="${APP_MUSIC:?APP_MUSIC is not set}"

  mkdir -p "${cfg_dir}/playlists" "${music_dir}"

  "@cmd@" --no-daemon "${cfg_dir}/mpd.conf" "$@"
}

main "$@"
